<a href="https://colab.research.google.com/github/RidwanSupon/Problem-Solving/blob/main/labfin1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy
arr = numpy.array([1,2,3,4,5,6,7,8,9])
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np  #numpy called in different name using "as"
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np  # numpy version check
print(np.__version__)

1.26.4


In [ ]:
import numpy as np
arr = np.array((1,2,3,4,5,7))
print(arr)
print(type(arr))

arr2 = np.array([1,2,3])
print(arr2)
print(type(arr2))

[1 2 3 4 5 7]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np     #0D
arr = np.array(405)
print(arr)

405


In [ ]:
import numpy as np  #1D
arr = np.array([405,101,1,21,34,121])
print(arr)

[405 101   1  21  34 121]


In [ ]:
import numpy as np     #2D
arr = np.array([[1,141,3,5,7,9], [2,3,5,4,8,7]])
print(arr)

[[  1 141   3   5   7   9]
 [  2   3   5   4   8   7]]


**Array_Indexing**

In [ ]:
import numpy as np     #3D with 2D
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[3])

4


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[3]+arr[1])

6


**Slicing**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:7])

[2 3 4 5 6 7]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[3:])

[4 5 6 7 8 9]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[:7])

[1 2 3 4 5 6 7]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[-3:-1])

[7 8]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:8:2])

[2 4 6 8]


**Numpy_data_type**

In [2]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1.1,1.2,3.3,2.9])
arr3 = np.array(['hasan','Rafiq'])

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)


int64
float64
<U5


In [10]:
import numpy as np
arr1 = np.array([1,2,3,4,5],dtype = 'i')
print(arr1)
print(arr1.dtype)

[1 2 3 4 5]
int32


In [12]:
import numpy as np # 4 byte integer
arr1 = np.array([1,2,3,4,5],dtype = 'i4')
print(arr1)
print(arr1.dtype)

[1 2 3 4 5]
int32


In [17]:
import numpy as np #Change data type from float to integer by using 'i' as parameter value:
arr = np.array([1.1,1.2,1.3,1.4,1.5])
newarray = arr.astype('i')
print(arr)
print(newarray)
print(newarray.dtype)

[1.1 1.2 1.3 1.4 1.5]
[1 1 1 1 1]
int32


In [16]:
import numpy as np # Change data type from integer to boolean:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


**Copy_VS_View**

In [20]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
newarr = arr.copy()
arr[0] = -1
print("array: ",+arr)
print("New array: ",+newarr)

array:  [-1  2  3  4  5  6  7]
New array:  [1 2 3 4 5 6 7]


In [21]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
newarr = arr.view()
arr[0] = -1
print("array: ",+arr)
print("New array: ",+newarr)

array:  [-1  2  3  4  5  6  7]
New array:  [-1  2  3  4  5  6  7]


**Shape**

In [22]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)

(2, 5)


In [27]:
#Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

import numpy as np
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


**Reshape**

In [32]:
#Convert the following 1-D array with 12 elements into a 2-D array.

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(3,4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
#Reshape From 1-D to 3-D

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


**Lab Task final:01**

In [ ]:
#1
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#2
import numpy as np
arr = np.array([[0,0,0],[0,0,0],[0,0,0]])
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
#3.1
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr[::]+5)

[ 5  6  7  8  9 10 11 12 13 14]


In [ ]:
#3.2
import numpy as np
arr = np.array([[1,2,3],[2,3,4]])
print(arr[::]*2)

[[2 4 6]
 [4 6 8]]


In [ ]:
#4
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
reshape_arr = arr.reshape(2,5)
print(reshape_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#5
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
reshape_arr = arr.reshape(2,5)
print(reshape_arr)
print(reshape_arr[1,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
8


In [ ]:
#6
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr[:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
