<a href="https://colab.research.google.com/github/RidwanSupon/Problem-Solving/blob/main/labfin1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy
arr = numpy.array([1,2,3,4,5,6,7,8,9])
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np  #numpy called in different name using "as"
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np  # numpy version check
print(np.__version__)

1.26.4


In [ ]:
import numpy as np
arr = np.array((1,2,3,4,5,7))
print(arr)
print(type(arr))

arr2 = np.array([1,2,3])
print(arr2)
print(type(arr2))

[1 2 3 4 5 7]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np     #0D
arr = np.array(405)
print(arr)

405


In [ ]:
import numpy as np  #1D
arr = np.array([405,101,1,21,34,121])
print(arr)

[405 101   1  21  34 121]


In [ ]:
import numpy as np     #2D
arr = np.array([[1,141,3,5,7,9], [2,3,5,4,8,7]])
print(arr)

[[  1 141   3   5   7   9]
 [  2   3   5   4   8   7]]


In [ ]:
import numpy as np     #3D with 2D
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[3])

4


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[3]+arr[1])

6


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:7])

[2 3 4 5 6 7]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[3:])

[4 5 6 7 8 9]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[:7])

[1 2 3 4 5 6 7]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[-3:-1])

[7 8]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:8:2])

[2 4 6 8]


**Lab Task final:01**

In [ ]:
#1
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#2
import numpy as np
arr = np.array([[0,0,0],[0,0,0],[0,0,0]])
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
#3.1
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr[::]+5)

[ 5  6  7  8  9 10 11 12 13 14]


In [ ]:
#3.2
import numpy as np
arr = np.array([[1,2,3],[2,3,4]])
print(arr[::]*2)

[[2 4 6]
 [4 6 8]]


In [ ]:
#4
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
reshape_arr = arr.reshape(2,5)
print(reshape_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#5
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
reshape_arr = arr.reshape(2,5)
print(reshape_arr)
print(reshape_arr[1,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
8


In [ ]:
#6
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr[:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
